{% set name = "texttable" %}
{% set version = "1.6.3" %}
{% set sha256 = "ce0faf21aa77d806bbff22b107cc22cce68dc9438f97a2df32c93e9afa4ce436" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  build:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - texttable

about:
  home: https://github.com/foutaise/texttable/
  license: LGPL-3.0
  license_family: LGPL
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Python module for creating simple ASCII tables
  description: texttable is a module to generate a formatted text table, using ASCII characters.
  doc_url: https://github.com/foutaise/texttable#documentation
  dev_url: https://github.com/foutaise/texttable/

extra:
  recipe-maintainers:
    - williamjamir
    - nicoddemus
    - micknudsen
