{% set name = "texttable" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d2068fb55115807d3ac77a4ca68fa48803e84ebb0ee2340f858107a36522638

build:
  number: 0
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  source_files:
    - tests.py
  imports:
    - texttable
  commands:
    - pip check
    - pytest -v tests.py
  requires:
    - pip
    - pytest

about:
  home: https://github.com/foutaise/texttable
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Python module for creating simple ASCII tables
  description: texttable is a module to generate a formatted text table, using ASCII characters.
  doc_url: https://github.com/foutaise/texttable#documentation
  dev_url: https://github.com/foutaise/texttable

extra:
  recipe-maintainers:
    - williamjamir
    - nicoddemus
    - micknudsen
