{% set name = "texttable" %}
{% set version = "1.1.0" %}
{% set sha256 = "50eff7f7af432b2e28c3be2f5bd60144837516f1ba63aac4b19f3257a7290c3f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - texttable

about:
  home: https://github.com/foutaise/texttable/
  license: LGPL-3.0
  license_family: LGPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Python module for creating simple ASCII tables
  description: texttable is a module to generate a formatted text table, using ASCII characters.
  doc_url: https://github.com/foutaise/texttable#documentation
  dev_url: https://github.com/foutaise/texttable/

extra:
  recipe-maintainers:
    - williamjamir
    - nicoddemus
