travis:
  secure:
    BINSTAR_TOKEN: Y0geO1MJjUEyS8ucKX0jfgg5E3KNLtvB1YMBEVYInetyxXdDT2W9NSzbtCfqknvPI38L9fKTNrQC/fRj+4MIpHsx4/1J1MLfnvUlNAXFWddsjdrd1eyRakomKuREZC3IeMaYLGNLiUxSWIzOrVSTdomokNVykvvf+kr9CDWJjleIdf8gsBPHVT6HCnGk820AilerlHq4HZxdsEvMjK0D88lC3qAVqTQ1c77au3LKm8Z3xzfKBLW31z8TNY6U61sJQMRuwxMarIGaIh+KCrYwq06D0mzowB0u9U/7Ppk86+6dxmPp6WH6KZvdiexaP5L27jdCoBEMCkyFIQ1mgK63R6PH/PKGGHYkjA5JM+3BleHyeMTkbCOVM6JCI+AEEt5AWhfi01qaQ0RV3+GxndGVjnqYMnRmI0WNj/thckZjRW9hjfG1I6w+5F1j+EPdhCoqr73GgNDS0+uOpuPEXLdasjO3GYNIV6fnq+1xPvWHrnR5eFkuS8lT4T1Gv3nC0nady3lHsVJMf7F59cPLPMXdaGVJomvdHx+s4xwsIKQHoOGGv+ZLuFUaQ0fFAxHQn2V9QiSvwrnbOyUfs68EX10SpxNIIDGfvgDxjdRa0HqjYd9i0EbW05B+vMl9dQVtMgfSn5u2mwxwPx5W8UmSP4gniykCc8hbywtzIYRzkcKbUnU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
