travis:
  secure:
    BINSTAR_TOKEN: APrwe38aUs6WTieQvlBBLMkEuZfrE4zg0Z1tuoUasCnt1ZlWlQB22IVnVo+Mw0yyCBBaiYuKglZV2M2+6Uc2fOoZ6zjf5BIfPxq8tyJb32gMmiAIUOyO7J7fzDRT6XegKabzmoo+/JskqZ0QQd8qzmEfJCqzAEHhGJ3i3GpLbEgpLnn+e59R2vInL/fDkslL387r91ylxwFlKUSGrUTqNfBREhPd4y8DQa+OfE/BkA60OQ4ObJJXYFmM4mDtk0BxT3hflgNIyReAyPU1ZUAk1gPzZHdL2SWF/wQXeljTJLcb3b0m2YsWDQQYm28r6GwDXdr8C9PC823syAiXwwBCG7uHmSQ1mfwvYl6gAhpGcwJvXAeYtlCkfEYHy3GsB7nRSpfYQtMPEFk9GlU43Wc84TlSqKTtCOhIj0zrnYwRu1h2TQFhnUkn/hOH04XjTMjsMza7LgJvG4oL9T5nGYmaaDHWODw2g6fa0a93cl+w1npqtNRtn36Swm6xZGYwBINhAjL9w7G0+pkE69apRdCgeygVcg5pkMGz8aJr1ypvIaKX1mzWFIaRLubVyr0NdasvM7hZ2pDuWqr2bQyU6DrMCYvhS8MeIpt9fRM9kGC865P1Kor4IqHDts0NOlm9G816SKt4EzHMP+lyU4FrmCj7ZqAww76KYXIcN8MExoEI4EY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
